spring:
  datasource:
    url: ${app.db.url}
    driver-class-name: org.h2.Driver
    username: ${app.db.username}
    password: ${app.db.password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    url: ${app.db.url}
    user: ${app.db.username}
    password: ${app.db.password}

server:
  port: 8080

app:
  jwtSecret: jwtsecret
  jwtExpirationInMs: 604800000
  db:
    url: jdbc:h2:mem:kalahdb
    username: sa
    password: password
